-- A holding: how many shares of one ticker a portfolio owns.
--
-- The unique constraint on (portfolio_id, ticker) is a safety net, not the implementation of the
-- additive-upsert rule. That rule lives in Portfolio.addStock; this constraint guarantees the
-- database can never end up with two rows for the same ticker even if that code is bypassed.
CREATE TABLE portfolio_stock (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    portfolio_id UUID        NOT NULL,
    ticker       VARCHAR(16) NOT NULL,
    shares       INTEGER     NOT NULL,
    CONSTRAINT pk_portfolio_stock PRIMARY KEY (id),
    CONSTRAINT fk_portfolio_stock_portfolio FOREIGN KEY (portfolio_id)
        REFERENCES portfolio (id) ON DELETE CASCADE,
    CONSTRAINT uq_portfolio_stock_ticker UNIQUE (portfolio_id, ticker),
    CONSTRAINT ck_portfolio_stock_shares_positive CHECK (shares > 0)
);

-- Every read of a portfolio loads its holdings by portfolio_id.
CREATE INDEX ix_portfolio_stock_portfolio_id ON portfolio_stock (portfolio_id);

COMMENT ON TABLE portfolio_stock IS 'A position in a single ticker within a portfolio.';
